/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ObjectSetModule"
 * 	found in "../protocol.asn1"
 */

#ifndef	_Color_H_
#define	_Color_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Color */
typedef struct Color {
	long	 red;
	long	 green;
	long	 blue;
	long	 alpha;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Color_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Color;

#ifdef __cplusplus
}
#endif

#endif	/* _Color_H_ */
