/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ObjectSetModule"
 * 	found in "../protocol.asn1"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_FileContent_H_
#define	_FileContent_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Object;

/* FileContent */
typedef struct FileContent {
	A_SEQUENCE_OF(struct Object) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FileContent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FileContent;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Object.h"

#endif	/* _FileContent_H_ */
