/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ObjectSetModule"
 * 	found in "../protocol.asn1"
 */

#ifndef	_GateTemplate_H_
#define	_GateTemplate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <VisibleString.h>
#include "Color.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GateTemplatePort;

/* GateTemplate */
typedef struct GateTemplate {
	INTEGER_t	 gate_id;
	INTEGER_t	 master_image_min_x;
	INTEGER_t	 master_image_min_y;
	INTEGER_t	 master_image_max_x;
	INTEGER_t	 master_image_max_y;
	VisibleString_t	 short_name;
	VisibleString_t	 description;
	Color_t	 fill_col;
	Color_t	 frame_col;
	struct GateTemplate__ports {
		A_SEQUENCE_OF(struct GateTemplatePort) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ports;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GateTemplate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GateTemplate;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GateTemplatePort.h"

#endif	/* _GateTemplate_H_ */
