/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ObjectSetModule"
 * 	found in "../protocol.asn1"
 */

#include <asn_internal.h>

#include "GateTemplatePort.h"

static asn_TYPE_member_t asn_MBR_GateTemplatePort_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GateTemplatePort, id),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GateTemplatePort, port_name),
		(ASN_TAG_CLASS_UNIVERSAL | (26 << 2)),
		0,
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"port-name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GateTemplatePort, port_type),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_PortType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"port-type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GateTemplatePort, relative_x_coord),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"relative-x-coord"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GateTemplatePort, relative_y_coord),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"relative-y-coord"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GateTemplatePort, col),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Color,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"col"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GateTemplatePort, diameter),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"diameter"
		},
};
static ber_tlv_tag_t asn_DEF_GateTemplatePort_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_GateTemplatePort_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 3 }, /* id at 110 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -1, 2 }, /* relative-x-coord at 113 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -2, 1 }, /* relative-y-coord at 114 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 6, -3, 0 }, /* diameter at 116 */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 2, 0, 0 }, /* port-type at 112 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, 0, 0 }, /* col at 115 */
    { (ASN_TAG_CLASS_UNIVERSAL | (26 << 2)), 1, 0, 0 } /* port-name at 111 */
};
static asn_SEQUENCE_specifics_t asn_SPC_GateTemplatePort_specs_1 = {
	sizeof(struct GateTemplatePort),
	offsetof(struct GateTemplatePort, _asn_ctx),
	asn_MAP_GateTemplatePort_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GateTemplatePort = {
	"GateTemplatePort",
	"GateTemplatePort",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GateTemplatePort_tags_1,
	sizeof(asn_DEF_GateTemplatePort_tags_1)
		/sizeof(asn_DEF_GateTemplatePort_tags_1[0]), /* 1 */
	asn_DEF_GateTemplatePort_tags_1,	/* Same as above */
	sizeof(asn_DEF_GateTemplatePort_tags_1)
		/sizeof(asn_DEF_GateTemplatePort_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GateTemplatePort_1,
	7,	/* Elements count */
	&asn_SPC_GateTemplatePort_specs_1	/* Additional specs */
};

