/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ObjectSetModule"
 * 	found in "../protocol.asn1"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Gate_H_
#define	_Gate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <VisibleString.h>
#include "TemplateOrientationType.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GatePort;

/* Gate */
typedef struct Gate {
	INTEGER_t	 min_x;
	INTEGER_t	 min_y;
	INTEGER_t	 max_x;
	INTEGER_t	 max_y;
	INTEGER_t	 gate_id;
	INTEGER_t	 id;
	INTEGER_t	 layer;
	VisibleString_t	 name;
	struct Gate__ports {
		A_SEQUENCE_OF(struct GatePort) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ports;
	TemplateOrientationType_t	 master_orientation;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Gate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Gate;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GatePort.h"

#endif	/* _Gate_H_ */
