/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ObjectSetModule"
 * 	found in "../protocol.asn1"
 */

#ifndef	_GatePort_H_
#define	_GatePort_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LogicModelConnection;

/* GatePort */
typedef struct GatePort {
	INTEGER_t	 port_id;
	struct GatePort__connections {
		A_SEQUENCE_OF(struct LogicModelConnection) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} connections;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GatePort_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GatePort;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LogicModelConnection.h"

#endif	/* _GatePort_H_ */
