/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ObjectSetModule"
 * 	found in "../protocol.asn1"
 */

#ifndef	_LogicModelConnection_H_
#define	_LogicModelConnection_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LogicModelConnection */
typedef struct LogicModelConnection {
	INTEGER_t	 object_id;
	INTEGER_t	 sub_id;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LogicModelConnection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LogicModelConnection;

#ifdef __cplusplus
}
#endif

#endif	/* _LogicModelConnection_H_ */
