/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ObjectSetModule"
 * 	found in "../protocol.asn1"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "Object.h"

static asn_TYPE_member_t asn_MBR_Object_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Object, choice.wire),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Wire,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"wire"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Object, choice.via),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Via,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"via"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Object, choice.gate),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Gate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Object, choice.gate_template),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GateTemplate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gate-template"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Object, choice.exclusion_area),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ExclusionArea,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"exclusion-area"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Object, choice.annotation),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Annotation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"annotation"
		},
};
static asn_TYPE_tag2member_t asn_MAP_Object_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* wire at 131 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* via at 132 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* gate at 133 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* gate-template at 134 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* exclusion-area at 135 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 } /* annotation at 137 */
};
static asn_CHOICE_specifics_t asn_SPC_Object_specs_1 = {
	sizeof(struct Object),
	offsetof(struct Object, _asn_ctx),
	offsetof(struct Object, present),
	sizeof(((struct Object *)0)->present),
	asn_MAP_Object_tag2el_1,
	6,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Object = {
	"Object",
	"Object",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_Object_1,
	6,	/* Elements count */
	&asn_SPC_Object_specs_1	/* Additional specs */
};

