/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ObjectSetModule"
 * 	found in "../protocol.asn1"
 */

#ifndef	_PortType_H_
#define	_PortType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PortType {
	PortType_in	= 0,
	PortType_out	= 1
} e_PortType;

/* PortType */
typedef ENUMERATED_t	 PortType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PortType;
asn_struct_free_f PortType_free;
asn_struct_print_f PortType_print;
asn_constr_check_f PortType_constraint;
ber_type_decoder_f PortType_decode_ber;
der_type_encoder_f PortType_encode_der;
xer_type_decoder_f PortType_decode_xer;
xer_type_encoder_f PortType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PortType_H_ */
