/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ObjectSetModule"
 * 	found in "../protocol.asn1"
 */

#include <asn_internal.h>

#include "Via.h"

static asn_TYPE_member_t asn_MBR_connections_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LogicModelConnection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_connections_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_connections_specs_9 = {
	sizeof(struct Via__connections),
	offsetof(struct Via__connections, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_connections_9 = {
	"connections",
	"connections",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_connections_tags_9,
	sizeof(asn_DEF_connections_tags_9)
		/sizeof(asn_DEF_connections_tags_9[0]), /* 1 */
	asn_DEF_connections_tags_9,	/* Same as above */
	sizeof(asn_DEF_connections_tags_9)
		/sizeof(asn_DEF_connections_tags_9[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_connections_9,
	1,	/* Single element */
	&asn_SPC_connections_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Via_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Via, x),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"x"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Via, y),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"y"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Via, diameter),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"diameter"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Via, direction),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_ViaDirection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"direction"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Via, id),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Via, layer),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"layer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Via, name),
		(ASN_TAG_CLASS_UNIVERSAL | (26 << 2)),
		0,
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Via, connections),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_connections_9,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"connections"
		},
};
static ber_tlv_tag_t asn_DEF_Via_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Via_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 4 }, /* x at 46 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 3 }, /* y at 47 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 2 }, /* diameter at 48 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -3, 1 }, /* id at 50 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 5, -4, 0 }, /* layer at 51 */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 3, 0, 0 }, /* direction at 49 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 7, 0, 0 }, /* connections at 53 */
    { (ASN_TAG_CLASS_UNIVERSAL | (26 << 2)), 6, 0, 0 } /* name at 52 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Via_specs_1 = {
	sizeof(struct Via),
	offsetof(struct Via, _asn_ctx),
	asn_MAP_Via_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Via = {
	"Via",
	"Via",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Via_tags_1,
	sizeof(asn_DEF_Via_tags_1)
		/sizeof(asn_DEF_Via_tags_1[0]), /* 1 */
	asn_DEF_Via_tags_1,	/* Same as above */
	sizeof(asn_DEF_Via_tags_1)
		/sizeof(asn_DEF_Via_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Via_1,
	8,	/* Elements count */
	&asn_SPC_Via_specs_1	/* Additional specs */
};

