/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ObjectSetModule"
 * 	found in "../protocol.asn1"
 */

#ifndef	_ViaDirection_H_
#define	_ViaDirection_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ViaDirection {
	ViaDirection_up	= 0,
	ViaDirection_down	= 1
} e_ViaDirection;

/* ViaDirection */
typedef ENUMERATED_t	 ViaDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ViaDirection;
asn_struct_free_f ViaDirection_free;
asn_struct_print_f ViaDirection_print;
asn_constr_check_f ViaDirection_constraint;
ber_type_decoder_f ViaDirection_decode_ber;
der_type_encoder_f ViaDirection_encode_der;
xer_type_decoder_f ViaDirection_decode_xer;
xer_type_encoder_f ViaDirection_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ViaDirection_H_ */
