/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ObjectSetModule"
 * 	found in "../protocol.asn1"
 */

#include <asn_internal.h>

#include "Wire.h"

static asn_TYPE_member_t asn_MBR_connections_10[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LogicModelConnection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_connections_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_connections_specs_10 = {
	sizeof(struct Wire__connections),
	offsetof(struct Wire__connections, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_connections_10 = {
	"connections",
	"connections",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_connections_tags_10,
	sizeof(asn_DEF_connections_tags_10)
		/sizeof(asn_DEF_connections_tags_10[0]), /* 1 */
	asn_DEF_connections_tags_10,	/* Same as above */
	sizeof(asn_DEF_connections_tags_10)
		/sizeof(asn_DEF_connections_tags_10[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_connections_10,
	1,	/* Single element */
	&asn_SPC_connections_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Wire_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Wire, from_x),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"from-x"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Wire, from_y),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"from-y"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Wire, to_x),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"to-x"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Wire, to_y),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"to-y"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Wire, diameter),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"diameter"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Wire, id),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Wire, layer),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"layer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Wire, name),
		(ASN_TAG_CLASS_UNIVERSAL | (26 << 2)),
		0,
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Wire, connections),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_connections_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"connections"
		},
};
static ber_tlv_tag_t asn_DEF_Wire_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Wire_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 6 }, /* from-x at 10 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 5 }, /* from-y at 11 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 4 }, /* to-x at 12 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -3, 3 }, /* to-y at 13 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -4, 2 }, /* diameter at 14 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 5, -5, 1 }, /* id at 15 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 6, -6, 0 }, /* layer at 16 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 8, 0, 0 }, /* connections at 18 */
    { (ASN_TAG_CLASS_UNIVERSAL | (26 << 2)), 7, 0, 0 } /* name at 17 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Wire_specs_1 = {
	sizeof(struct Wire),
	offsetof(struct Wire, _asn_ctx),
	asn_MAP_Wire_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Wire = {
	"Wire",
	"Wire",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Wire_tags_1,
	sizeof(asn_DEF_Wire_tags_1)
		/sizeof(asn_DEF_Wire_tags_1[0]), /* 1 */
	asn_DEF_Wire_tags_1,	/* Same as above */
	sizeof(asn_DEF_Wire_tags_1)
		/sizeof(asn_DEF_Wire_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Wire_1,
	9,	/* Elements count */
	&asn_SPC_Wire_specs_1	/* Additional specs */
};

